GUI_ZOOM_IN = "Zoom IN"
GUI_ZOOM_OUT = "Zoom OUT"
GUI_ZOOM_ORG = "Zoom ORG"
GUI_ZOOM_MAX = "Zoom MAX"

GUI_CAMERA_PREVIEW = "Camera"
GUI_CAMERA_PAUSE = "Pause"
GUI_CAMERA_SNAPSHOT = "Snapshot"
GUI_CAMERA_RECORD = "Record"
GUI_CAMERA_STOP = "STOP REC"

WINDOW_OFFSET_RIGHT = 180
WINDOW_OFFSET_BOTTOM = 50
WINDOW_OFFSET_LEFT = 4
MIN_SCALE = 0.2
MAX_SCALE = 4

BOSON_WIDTH = 640
BOSON_HEIGHT = 512

MAX_FRAMES = 3000
FRAME_SIZE_IN_BYTES = 655360 #640*512*2
MAX_VIDEO_SIZE = MAX_FRAMES * FRAME_SIZE_IN_BYTES

SINGLE_IMAGE = 1
SEQUENCE_OF_IMAGES = 100

FAST_PREVIEW_STEP = 10


RED = [1, 0, 0, 1]
BLACK = [0, 0, 0, 1]
WHITE = [1, 1, 1, 1]

DEFAULT_BUTTON_BACKGROUND_COLOR = BLACK

MAX_POIS = 2
MAX_RECTANGLES = 10

DRAWING_MODE_POINT = 1
DRAWING_MODE_POI = 5
DRAWING_MODE_LINE = 10
DRAWING_MODE_RECT = 100

FOLDER_LABELS = "./data"

